apiVersion: voyager.appscode.com/v1beta1
kind: Ingress
metadata:
  name: proxy
  namespace: default
  annotations:
    ingress.appscode.com/type: NodePort
    ingress.appscode.com/stats: "true"
    ingress.appscode.com/max-connections: "32000"
spec:
  # For resources, see https://github.com/appscode/voyager/issues/1267.
  resources:
    requests:
      memory: "0.2Gi"
      cpu: "1"
    limits:
      memory: "0.2Gi"
      cpu: "1"
  backend:
      serviceName: api-liveramp
      servicePort: '8080'
  rules:
  - host: /
    http:
      paths:
      - path: /
        backend:
          serviceName: api-liveramp
          servicePort: '8080'
  frontendRules:
  - port: 80
    rules:
    - 'maxconn 6000'
  - port: 443
    rules:
    - 'maxconn 6000'
