apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  namespace: default
  name: hello
  labels:
    app: hello-service
spec:
  revisionHistoryLimit: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 0
  replicas: 10
  selector:
    matchLabels:
      app: hello-service
  template:
    metadata:
      labels:
        app: hello-service
    spec:
      containers:
        - name: hello-service
          image: gcr.io/liveramp-eng/hello:latest
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "0.5Gi"
              cpu: "0.5"
            limits:
              memory: "0.5Gi"
              cpu: "1"
